package org.cj.dao.auto;

import org.cj.entity.auto.UserBean;

public interface UserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_user
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_user
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    int insert(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_user
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    int insertSelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_user
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    UserBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_user
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    int updateByPrimaryKeySelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_user
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    int updateByPrimaryKey(UserBean record);
}