package org.cj.entity.auto;

import java.util.Date;

public class UserBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.id
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.name
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.password
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.salt
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.is_del
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private Byte isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.created_by
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.created_date
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.updated_by
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_user.updated_date
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.id
     *
     * @return the value of shiro_user.id
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.id
     *
     * @param id the value for shiro_user.id
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.name
     *
     * @return the value of shiro_user.name
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.name
     *
     * @param name the value for shiro_user.name
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.password
     *
     * @return the value of shiro_user.password
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.password
     *
     * @param password the value for shiro_user.password
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.salt
     *
     * @return the value of shiro_user.salt
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.salt
     *
     * @param salt the value for shiro_user.salt
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.is_del
     *
     * @return the value of shiro_user.is_del
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.is_del
     *
     * @param isDel the value for shiro_user.is_del
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.created_by
     *
     * @return the value of shiro_user.created_by
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.created_by
     *
     * @param createdBy the value for shiro_user.created_by
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.created_date
     *
     * @return the value of shiro_user.created_date
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.created_date
     *
     * @param createdDate the value for shiro_user.created_date
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.updated_by
     *
     * @return the value of shiro_user.updated_by
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.updated_by
     *
     * @param updatedBy the value for shiro_user.updated_by
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_user.updated_date
     *
     * @return the value of shiro_user.updated_date
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_user.updated_date
     *
     * @param updatedDate the value for shiro_user.updated_date
     *
     * @mbggenerated Thu Sep 13 23:14:40 CST 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}